apiVersion: v1
kind: ReplicationController 
metadata:
  name: mylogin-rc

spec:
  replicas: 4
  selector: 
    app: mylogin
  template:
    metadata:
      labels:
        app: mylogin

    spec:
      containers:
      - name: mynginx-container
        image: vinaydock009/javaimage:1
        ports:
        - containerPort: 8080