apiVersion: v1
kind: ReplicationController 
metadata:
  name: myapp-rc

spec:
  replicas: 4
  selector: 
    app: myapp
  template:
    metadata:
      labels:
        app: myapp

    spec:
      containers:
      - name: mynginx-container
        image: nginx
        ports:
        - containerPort: 8080